//
export const imovelExemplo = (code) => ({
  property_id: null,
  floor: null,
  address_visibility: 8,
  agent: {
    label: "John Doe",
    person_id: 1593148,
    image: "images/user_default.png",
  },
  agency_date: "2022-03-24",
  email_time_gap: null,
  building_status: 3,
  building_type: null,
  city: 8521,
  cleaning_fee_price: null,
  surety_fire_price: null,
  code: code,
  editable_code: code,
  complement: "",
  condominium: null,
  condominium_price: null,
  condominium_price_visible: false,
  condominium_is_exempt: false,
  contracts: [
    {
      id: 1,
      price: 66000000,
      visible: false,
      commission_percentage: 0,
      commission_cents: 0,
      amount_type: 1,
      unavailable_reason: null,
      available: true,
      index_base_value: null,
      index_readjustment_id: null,
    },
  ],
  deadline_date: null,
  exclusivity: false,
  exclusivity_date: "2022-03-24",
  garages: 2,
  suites: 1,
  bedrooms: 3,
  bathrooms: 2,
  position: null,
  facilities: [14, 54, 12, 91, 92, 30, 51],
  facilitiesGroups: [],
  floor_types: [],
  solar_orientations: [],
  total_area: 127,
  useful_area: null,
  arable_area: null,
  financeable: 1,
  furnished: 0,
  interchange: false,
  iptu_price: null,
  iptu_record: "",
  iptu_visible: false,
  iptu_monthly: false,
  iptu_is_exempt: false,
  latitude: -26.2919485,
  longitude: -48.9053641,
  neighborhood: 14057,
  number: `[${code}]`,
  title: "Sobrado Geminado à Venda no Vila nova",
  observation_external:
    "Sobrado Geminado TOP no Vila Nova medindo 127 m2 contendo suíte + 02 dorm, copa e cozinha com ambientes integrados com a sala de estar, área aberta com churrasqueira, pergolado e piscina, móveis sob medida, ótimo acabamento com piso porcelanato, gesso rebaixado, laminado na parte superior, em excelente localização próximo de mercados, escola, posto de saúde, etc. Agende já uma visita!",
  meta_title: "",
  meta_description: "",
  observation_internal:
    "GERSON PROPRIETÁRIO FONE 99975-9742\nOPÇÃO JEFERSON\nINÍCIO ANUNCIO 17/03/2022\n--------------------------------------------------------------------------------\nAtributos sistema Imobland\n\n ➜ Geminado\n ➜ Lavabo\n ➜ Churrasqueira\n ➜ Piscina\n ➜ Espaço Gourmet\n ➜ Sala de estar\n ➜ Sala de jantar\n ➜ Cozinha\n ➜ Closet \n ➜ Copa\n ➜ Lavanderia\n ➜ Aceita financiamento\n\n ➜ Área total - m²: 127\n ➜ Suíte(s): 1\n ➜ Vagas na garagem: 2\n ➜ Banheiro(s): 2\n ➜ Quarto(s): 3\n ➜ Piso: Porcelanato\n ➜ Forro: Laje\n ➜ Material: Alvenaria\n ➜ Estado do imóvel: Semi-novo\n ➜ Sacada: Sacada\n\n ➜ Fonte: http://admin.imobland.com.br/property/83438/edit",
  person_owners: [
    {
      person: { person_id: 1593152, name: "Imobiliária Vila Nova" },
      percentage: 100,
      sendUpdateEmail: false,
    },
  ],
  people_quantity: null,
  private_area: null,
  property_board: false,
  registration_record: "",
  water_record: "",
  gas_record: "",
  energy_record: "",
  broker: {
    label: "Jetimob",
    person_id: 0,
    image: "images/user_default.png",
    user_system_id: 23215,
    deleted: false,
  },
  rural_activity: [],
  rural_headquarters: null,
  sea_distance: null,
  occupation: 1,
  season_calendars: [],
  season_unavailable: [],
  state: 22,
  reference: "",
  street: "Rua não cadastrada",
  street_id: null,
  surety_warranty: false,
  labels: [],
  terrain_total_area: null,
  terrain_length_left: null,
  terrain_length_right: null,
  terrain_width_back: null,
  terrain_width_front: null,
  ceiling_height: null,
  type: 20,
  typeCategory: "Residencial",
  approved: true,
  zipcode: null,
  keys: [],
  map_visibility: 0,
  images: [
    {
      name: null,
      size: 172829,
      url: "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8v2AJ5BK_M2NRlAfppBQAdtKDLk2MSVD3yuFPpkqWMrnsQJZzBkN6yuUCTPigmHGhw4-DYgS0/1647882838.",
      fullsizeUrl:
        "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8p2OIdekopXlWDY5-MAAMBV0DPcGUSUdlVOu8v0SZt8IGvmKLbDCL1wwZRxSQkxv4KzMJ4HG1e/1647882838.",
      selected: false,
      id: 18892789,
      visible: true,
    },
    {
      name: null,
      size: 149574,
      url: "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8v2AJ5BK_M2NRlAfppBQAdtKDLk2MSVD3KYbaWVsYSlF7tAGbcaF9zP31I-S4mJZRzj8U0xbE/1647882839.",
      fullsizeUrl:
        "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8p2OIdekopXlWDY5-MAAMBV0DPcGUSUdlVAjbKruIObruKZYchEdp0AoBsHuMixucWzy7SVU1z/1647882839.",
      selected: false,
      id: 18892791,
      visible: true,
    },
    {
      name: null,
      size: 287532,
      url: "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8v2AJ5BK_M2NRlAfppBQAdtKDLk2MSVD2q4DJuaN0Trf5RH2GeKllz_PuWBi4mH_FwxmyPeVo/1647882840.",
      fullsizeUrl:
        "https://s01.jetimgs.com/trvAWQHuYcArjvEQrh93oEZSAxK0Jz8p2OIdekopXlWDY5-MAAMBV0DPcGUSUdlVYrdOVtwVb4Iq2ZgmU5hyAkPqwBwixv29zOXxKzJA/1647882840.",
      selected: false,
      id: 18892794,
      visible: true,
    },
  ],
  blueprints: [],
  files_ids: [],
  tours: [],
  videos: [],
  unapproval_observation: null,
  boxes: [],
  google_earth_url: null,
  portal_property: {
    "126": {
      active: false,
      highlight: { label: "Sem destaque", value: 0 },
      portal_property_id: null,
    },
    "153": {
      active: false,
      highlight: { label: "Sem destaque", value: 0 },
      portal_property_id: null,
    },
    "181": {
      active: false,
      highlight: { label: "Sem destaque", value: 0 },
      portal_property_id: null,
    },
    "6349": {
      active: true,
      highlight: { label: "Sem destaque", value: 0 },
      portal_property_id: 5473372,
    },
  },
  index_readjustment: null,
  index_readjustment_base_value: null,
  owner: null,
  origin: false,
});
