type Agent = {
  label: string;
  person_id: number;
  image: string;
};

type Image = {
  name: string;
  size: number;
  url: string;
  fullsizeUrl: string;
  selected: boolean;
  id: number;
  visible: boolean;
};

type Broker = {
  label: string;
  person_id: number;
  image: string;
  user_system_id: number;
  deleted: boolean;
};

type Person = {
  person: {
    person_id: number;
    name: string;
  };
  percentage: number;
  sendUpdateEmail: boolean;
};

type Contract = {
  id: number;
  price: number;
  visible: boolean;
  commission_percentage: number;
  commission_cents: number;
  amount_type: number;
  unavailable_reason: boolean;
  available: boolean;
  index_base_value: number;
  index_readjustment_id: number;
};

type PropertyType = {
  property_id: number;
  floor: number;
  address_visibility: number;
  agent: Agent;
  agency_date: string;
  email_time_gap: string;
  building_status: number;
  building_type: number;
  city: number;
  cleaning_fee_price: number;
  surety_fire_price: number;
  code: string;
  editable_code: string;
  complement: string;
  condominium: number;
  condominium_price: number;
  condominium_price_visible: boolean;
  condominium_is_exempt: boolean;
  contracts: Contract[];
  deadline_date: string;
  exclusivity: boolean;
  exclusivity_date: string;
  garages: number;
  suites: number;
  bedrooms: number;
  bathrooms: number;
  position: string;
  facilities: number[];
  facilitiesGroups: any[];
  floor_types: any[];
  solar_orientations: any[];
  total_area: number;
  useful_area: number;
  arable_area: number;
  financeable: number;
  furnished: number;
  interchange: boolean;
  iptu_price: number;
  iptu_record: string;
  iptu_visible: boolean;
  iptu_monthly: boolean;
  iptu_is_exempt: boolean;
  latitude: number;
  longitude: number;
  neighborhood: number;
  number: string;
  title: string;
  observation_external: string;
  meta_title: string;
  meta_description: string;
  observation_internal: string;
  person_owners: Person[];
  people_quantity: number;
  private_area: number;
  property_board: boolean;
  registration_record: string;
  water_record: string;
  gas_record: string;
  energy_record: string;
  broker: Broker;
  rural_activity: [];
  rural_headquarters: number;
  sea_distance: number;
  occupation: number;
  season_calendars: [];
  season_unavailable: [];
  state: number;
  reference: string;
  street: string;
  street_id: number;
  surety_warranty: boolean;
  labels: any[];
  terrain_total_area: number;
  terrain_length_left: number;
  terrain_length_right: number;
  terrain_width_back: number;
  terrain_width_front: number;
  ceiling_height: number;
  type: number;
  typeCategory: string;
  approved: boolean;
  zipcode: string;
  keys: any[];
  map_visibility: number;
  images: Image[];
  blueprints: any[];
  files_ids: any[];
  tours: any[];
  videos: any[];
  unapproval_observation: string;
  boxes: any[];
  google_earth_url: string;
  portal_property: any;
  index_readjustment: string;
  index_readjustment_base_value: number;
  owner: any;
  origin: boolean;
};
